using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;

namespace Azure4Alexa
{
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes
            config.MapHttpAttributeRoutes();

            // The following code block is part of the template generated by Visual Studio
            // we don't need it for our project. re-enable if you need to. 

            //config.Routes.MapHttpRoute(
            //    name: "DefaultApi",
            //    routeTemplate: "api/{controller}/{id}",
            //    defaults: new { id = RouteParameter.Optional }
            //);
        }
    }
}
